# Generated by Django 3.2.10 on 2021-12-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
