# Generated by Django 3.2.10 on 2021-12-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_book_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.ImageField(blank=True, upload_to='code'),
        ),
    ]
