# Generated by Django 3.2.10 on 2021-12-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211221_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='order_id',
        ),
    ]
