# Generated by Django 3.2.10 on 2021-12-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211221_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
