# Generated by Django 3.2.10 on 2021-12-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_book_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_refunded',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
