# Generated by Django 4.0 on 2021-12-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railapp', '0002_answers_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=30)),
                ('manager', models.CharField(default='', max_length=10)),
                ('assistant_manager', models.CharField(default='', max_length=10)),
                ('rpf', models.CharField(default='', max_length=10)),
                ('deputy_rpf', models.CharField(default='', max_length=10)),
                ('head_officer', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('run_days', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_destination', to='railapp.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_source', to='railapp.station')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='answers',
            order_with_respect_to='question',
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.TimeField()),
                ('departure', models.TimeField()),
                ('distance', models.IntegerField()),
                ('day', models.IntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railapp.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railapp.train')),
            ],
        ),
    ]
