# Generated by Django 3.2.10 on 2021-12-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railapp', '0003_station_train_remove_questions_slug_trainschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='train',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='train',
            name='source',
        ),
        migrations.RemoveField(
            model_name='trainschedule',
            name='station',
        ),
        migrations.RemoveField(
            model_name='trainschedule',
            name='train',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
        migrations.DeleteModel(
            name='TrainSchedule',
        ),
    ]
